// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NeverLate_api.Persistence.Database;
using NeverLate.IntegrationTests;

#nullable disable

namespace NeverLate_api.Migrations.IntegrationTests.Migrations
{
    [DbContext(typeof(TestNeverLateContext))]
    [Migration("20220609193505_AddNormalisedUsernameColumn")]
    partial class AddNormalisedUsernameColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4d6a04f5-f5f5-4267-9797-6db304f04105",
                            Email = "test_user_1@test.com",
                            NormalizedEmail = "TEST_USER_1@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOQDwWuMGBlh/rmc2WTAM86K0+js0GxcPzISxN4dGan+4epO334YviOGICRArUZhgw==",
                            UserName = "test_user_1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
