// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeverLate_api.Persistence.Database;

#nullable disable

namespace NeverLate_api.Migrations
{
    [DbContext(typeof(NeverLateContext))]
    [Migration("20230919172303_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "74979eb5-e6a5-448f-ae1e-99ab4b1ae45c",
                            Email = "test_user_1@test.com",
                            NormalizedEmail = "TEST_USER_1@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIbcaZ9tGcvho9yA/4y4T+cAEZBjBVSy1mH9gN9CoyfVaVGOA6uGhdXsHbb8bOGp0g==",
                            UserName = "test_user_1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
