services:
  db:
    image: mysql:8.0-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - never-late-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '80:80'
volumes:
  never-late-db: 
    